// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sign.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignRawRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Domain               uint64   `protobuf:"varint,3,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignRawRequest) Reset()         { *m = SignRawRequest{} }
func (m *SignRawRequest) String() string { return proto.CompactTextString(m) }
func (*SignRawRequest) ProtoMessage()    {}
func (*SignRawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3feb3e12a3dc7fb1, []int{0}
}

func (m *SignRawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignRawRequest.Unmarshal(m, b)
}
func (m *SignRawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignRawRequest.Marshal(b, m, deterministic)
}
func (m *SignRawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRawRequest.Merge(m, src)
}
func (m *SignRawRequest) XXX_Size() int {
	return xxx_messageInfo_SignRawRequest.Size(m)
}
func (m *SignRawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignRawRequest proto.InternalMessageInfo

func (m *SignRawRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SignRawRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SignRawRequest) GetDomain() uint64 {
	if m != nil {
		return m.Domain
	}
	return 0
}

type SignRawResponse struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignRawResponse) Reset()         { *m = SignRawResponse{} }
func (m *SignRawResponse) String() string { return proto.CompactTextString(m) }
func (*SignRawResponse) ProtoMessage()    {}
func (*SignRawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3feb3e12a3dc7fb1, []int{1}
}

func (m *SignRawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignRawResponse.Unmarshal(m, b)
}
func (m *SignRawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignRawResponse.Marshal(b, m, deterministic)
}
func (m *SignRawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRawResponse.Merge(m, src)
}
func (m *SignRawResponse) XXX_Size() int {
	return xxx_messageInfo_SignRawResponse.Size(m)
}
func (m *SignRawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignRawResponse proto.InternalMessageInfo

func (m *SignRawResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*SignRawRequest)(nil), "v1.SignRawRequest")
	proto.RegisterType((*SignRawResponse)(nil), "v1.SignRawResponse")
}

func init() { proto.RegisterFile("sign.proto", fileDescriptor_3feb3e12a3dc7fb1) }

var fileDescriptor_3feb3e12a3dc7fb1 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xce, 0x4c, 0xcf,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x54, 0x0a, 0xe3, 0xe2, 0x0b, 0x06,
	0x8a, 0x04, 0x25, 0x96, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x49, 0x70, 0xb1, 0x27,
	0x26, 0x27, 0xe7, 0x97, 0xe6, 0x95, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x42,
	0x42, 0x5c, 0x2c, 0x29, 0x89, 0x25, 0x89, 0x12, 0x4c, 0x40, 0x61, 0x9e, 0x20, 0x30, 0x5b, 0x48,
	0x8c, 0x8b, 0x2d, 0x25, 0x3f, 0x37, 0x31, 0x33, 0x4f, 0x82, 0x19, 0x28, 0xca, 0x12, 0x04, 0xe5,
	0x29, 0xe9, 0x73, 0xf1, 0xc3, 0xcd, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x92, 0xe1, 0xe2,
	0x04, 0x59, 0x9e, 0x58, 0x52, 0x5a, 0x94, 0x0a, 0x36, 0x9a, 0x27, 0x08, 0x21, 0x60, 0x64, 0xc3,
	0xc5, 0x02, 0xd2, 0x20, 0x64, 0xc2, 0xc5, 0x0e, 0xd5, 0x28, 0x24, 0xa4, 0x57, 0x66, 0xa8, 0x87,
	0xea, 0x3a, 0x29, 0x61, 0x14, 0x31, 0x88, 0xc9, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x1f, 0x19, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x57, 0xa9, 0x62, 0x43, 0xdf, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SignClient is the client API for Sign service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SignClient interface {
	SignRaw(ctx context.Context, in *SignRawRequest, opts ...grpc.CallOption) (*SignRawResponse, error)
}

type signClient struct {
	cc *grpc.ClientConn
}

func NewSignClient(cc *grpc.ClientConn) SignClient {
	return &signClient{cc}
}

func (c *signClient) SignRaw(ctx context.Context, in *SignRawRequest, opts ...grpc.CallOption) (*SignRawResponse, error) {
	out := new(SignRawResponse)
	err := c.cc.Invoke(ctx, "/v1.Sign/SignRaw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignServer is the server API for Sign service.
type SignServer interface {
	SignRaw(context.Context, *SignRawRequest) (*SignRawResponse, error)
}

// UnimplementedSignServer can be embedded to have forward compatible implementations.
type UnimplementedSignServer struct {
}

func (*UnimplementedSignServer) SignRaw(ctx context.Context, req *SignRawRequest) (*SignRawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignRaw not implemented")
}

func RegisterSignServer(s *grpc.Server, srv SignServer) {
	s.RegisterService(&_Sign_serviceDesc, srv)
}

func _Sign_SignRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignServer).SignRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Sign/SignRaw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignServer).SignRaw(ctx, req.(*SignRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sign_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Sign",
	HandlerType: (*SignServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignRaw",
			Handler:    _Sign_SignRaw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sign.proto",
}
