// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UnlockWalletRequest struct {
	Wallet               string   `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Passphrase           []byte   `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockWalletRequest) Reset()         { *m = UnlockWalletRequest{} }
func (m *UnlockWalletRequest) String() string { return proto.CompactTextString(m) }
func (*UnlockWalletRequest) ProtoMessage()    {}
func (*UnlockWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{0}
}

func (m *UnlockWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockWalletRequest.Unmarshal(m, b)
}
func (m *UnlockWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockWalletRequest.Marshal(b, m, deterministic)
}
func (m *UnlockWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockWalletRequest.Merge(m, src)
}
func (m *UnlockWalletRequest) XXX_Size() int {
	return xxx_messageInfo_UnlockWalletRequest.Size(m)
}
func (m *UnlockWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockWalletRequest proto.InternalMessageInfo

func (m *UnlockWalletRequest) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

func (m *UnlockWalletRequest) GetPassphrase() []byte {
	if m != nil {
		return m.Passphrase
	}
	return nil
}

type LockWalletRequest struct {
	Wallet               string   `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockWalletRequest) Reset()         { *m = LockWalletRequest{} }
func (m *LockWalletRequest) String() string { return proto.CompactTextString(m) }
func (*LockWalletRequest) ProtoMessage()    {}
func (*LockWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{1}
}

func (m *LockWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockWalletRequest.Unmarshal(m, b)
}
func (m *LockWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockWalletRequest.Marshal(b, m, deterministic)
}
func (m *LockWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockWalletRequest.Merge(m, src)
}
func (m *LockWalletRequest) XXX_Size() int {
	return xxx_messageInfo_LockWalletRequest.Size(m)
}
func (m *LockWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LockWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LockWalletRequest proto.InternalMessageInfo

func (m *LockWalletRequest) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

type ListAccountsRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{2}
}

func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(m, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

func (m *ListAccountsRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Account struct {
	Uuid                 []byte   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{3}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type ListAccountsResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListAccountsResponse) Reset()         { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()    {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{4}
}

func (m *ListAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsResponse.Unmarshal(m, b)
}
func (m *ListAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsResponse.Marshal(b, m, deterministic)
}
func (m *ListAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsResponse.Merge(m, src)
}
func (m *ListAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAccountsResponse.Size(m)
}
func (m *ListAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsResponse proto.InternalMessageInfo

func (m *ListAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func init() {
	proto.RegisterType((*UnlockWalletRequest)(nil), "v1.UnlockWalletRequest")
	proto.RegisterType((*LockWalletRequest)(nil), "v1.LockWalletRequest")
	proto.RegisterType((*ListAccountsRequest)(nil), "v1.ListAccountsRequest")
	proto.RegisterType((*Account)(nil), "v1.Account")
	proto.RegisterType((*ListAccountsResponse)(nil), "v1.ListAccountsResponse")
}

func init() { proto.RegisterFile("wallet.proto", fileDescriptor_b88fd140af4deb6f) }

var fileDescriptor_b88fd140af4deb6f = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x51, 0xcf, 0x4b, 0xfb, 0x30,
	0x14, 0xdf, 0x2f, 0xfa, 0xfd, 0xee, 0xad, 0x17, 0x33, 0x9d, 0xa5, 0xa2, 0x48, 0x2e, 0x4e, 0x84,
	0x8c, 0xcd, 0x83, 0x07, 0x0f, 0x22, 0xe2, 0xc9, 0x0a, 0x52, 0x10, 0x8f, 0x92, 0xd6, 0xb8, 0x95,
	0x75, 0x4d, 0x5c, 0x92, 0x49, 0xff, 0x3e, 0xff, 0x31, 0x9b, 0xa4, 0x93, 0x89, 0x3b, 0xe8, 0xed,
	0xe5, 0xf3, 0xe3, 0xbd, 0xbc, 0xcf, 0x03, 0xff, 0x9d, 0xe6, 0x39, 0x53, 0x44, 0x2c, 0xb9, 0xe2,
	0xa8, 0xb5, 0x1a, 0x87, 0x07, 0x53, 0xce, 0xa7, 0x39, 0x1b, 0x59, 0x24, 0xd1, 0xaf, 0x23, 0xb6,
	0x10, 0xaa, 0x74, 0x02, 0x7c, 0x0f, 0xfd, 0xc7, 0x22, 0xe7, 0xe9, 0xfc, 0xc9, 0xda, 0x62, 0xf6,
	0xa6, 0x99, 0x54, 0x68, 0x00, 0x9e, 0xeb, 0x13, 0x34, 0x8f, 0x9b, 0xc3, 0x6e, 0x5c, 0xbf, 0xd0,
	0x11, 0x80, 0xa0, 0x52, 0x8a, 0xd9, 0x92, 0x4a, 0x16, 0xb4, 0x2a, 0xce, 0x8f, 0x37, 0x10, 0x7c,
	0x06, 0x3b, 0xd1, 0x6f, 0x9b, 0xe1, 0x53, 0xe8, 0x47, 0x99, 0x54, 0xd7, 0x69, 0xca, 0x75, 0xa1,
	0xe4, 0x5a, 0x8e, 0xa0, 0x23, 0xa8, 0x9a, 0xd5, 0x62, 0x5b, 0xe3, 0x07, 0xf8, 0x57, 0xcb, 0x0c,
	0xad, 0x75, 0xf6, 0x62, 0x69, 0x3f, 0xb6, 0xb5, 0xc1, 0x0a, 0xba, 0x70, 0x1f, 0xaa, 0x2c, 0xa6,
	0x46, 0x87, 0xd5, 0x57, 0x75, 0x92, 0x67, 0xe9, 0xf3, 0x9c, 0x95, 0x41, 0xdb, 0xaa, 0xbb, 0x0e,
	0xb9, 0x63, 0x25, 0xbe, 0x82, 0xdd, 0xef, 0xc3, 0xa5, 0xe0, 0x85, 0x64, 0xe8, 0x04, 0xfe, 0xd3,
	0x1a, 0xab, 0x46, 0xb4, 0x87, 0xbd, 0x49, 0x8f, 0xac, 0xc6, 0xa4, 0xd6, 0xc5, 0x5f, 0xe4, 0xe4,
	0xa3, 0x09, 0x9e, 0xdb, 0x13, 0x5d, 0x82, 0xe7, 0x42, 0x44, 0xfb, 0x46, 0xbb, 0x25, 0xd0, 0x70,
	0x40, 0xdc, 0x15, 0xc8, 0xfa, 0x0a, 0xe4, 0xd6, 0x5c, 0x01, 0x37, 0xd0, 0x05, 0x74, 0x4c, 0x64,
	0x68, 0xcf, 0x58, 0xa3, 0x3f, 0x18, 0x6f, 0xc0, 0xdf, 0xdc, 0xc0, 0xcd, 0xde, 0x12, 0x68, 0x18,
	0xfc, 0x24, 0xdc, 0xb2, 0xb8, 0x91, 0x78, 0xb6, 0xed, 0xf9, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x4e, 0x0e, 0xeb, 0x8a, 0x37, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletClient interface {
	Unlock(ctx context.Context, in *UnlockWalletRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Lock(ctx context.Context, in *LockWalletRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
}

type walletClient struct {
	cc *grpc.ClientConn
}

func NewWalletClient(cc *grpc.ClientConn) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) Unlock(ctx context.Context, in *UnlockWalletRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/v1.Wallet/Unlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) Lock(ctx context.Context, in *LockWalletRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/v1.Wallet/Lock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, "/v1.Wallet/ListAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServer is the server API for Wallet service.
type WalletServer interface {
	Unlock(context.Context, *UnlockWalletRequest) (*empty.Empty, error)
	Lock(context.Context, *LockWalletRequest) (*empty.Empty, error)
	ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
}

// UnimplementedWalletServer can be embedded to have forward compatible implementations.
type UnimplementedWalletServer struct {
}

func (*UnimplementedWalletServer) Unlock(ctx context.Context, req *UnlockWalletRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unlock not implemented")
}
func (*UnimplementedWalletServer) Lock(ctx context.Context, req *LockWalletRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lock not implemented")
}
func (*UnimplementedWalletServer) ListAccounts(ctx context.Context, req *ListAccountsRequest) (*ListAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccounts not implemented")
}

func RegisterWalletServer(s *grpc.Server, srv WalletServer) {
	s.RegisterService(&_Wallet_serviceDesc, srv)
}

func _Wallet_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Wallet/Unlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).Unlock(ctx, req.(*UnlockWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Wallet/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).Lock(ctx, req.(*LockWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Wallet/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unlock",
			Handler:    _Wallet_Unlock_Handler,
		},
		{
			MethodName: "Lock",
			Handler:    _Wallet_Lock_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _Wallet_ListAccounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet.proto",
}
